/**
 * This file is generated by jsonrpcstub, DO NOT CHANGE IT MANUALLY!
 */

#ifndef JSONRPC_CPP_STUB_CIA_SUBPUB_PUBLISH_CLIENT_H_
#define JSONRPC_CPP_STUB_CIA_SUBPUB_PUBLISH_CLIENT_H_

#include <jsonrpccpp/client.h>

namespace cia_subpub {
    class publish_client : public jsonrpc::Client
    {
        public:
            publish_client(jsonrpc::IClientConnector &conn, jsonrpc::clientVersion_t type = jsonrpc::JSONRPC_CLIENT_V2) : jsonrpc::Client(conn, type) {}

            void publish(const std::string& channel, int event_id) throw (jsonrpc::JsonRpcException)
            {
                Json::Value p;
                p["channel"] = channel;
                p["event_id"] = event_id;
                this->CallNotification("publish",p);
            }
    };

}
#endif //JSONRPC_CPP_STUB_CIA_SUBPUB_PUBLISH_CLIENT_H_
